version: "3"
services:
  app:
    image: zio-jwt-starter:latest
    container_name: app
    expose:
      - APP_PORT
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    expose:
      - POSTGRES_PORT
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/main/sql:/docker-entrypoint-initdb.d/:ro
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin
    restart: always
    expose:
      - 5050
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: